version: '3.8'
services:
  api:
    build: ./server
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:jammy
    ports:
      - "27017:27017"
    